[2025-03-21T21:19:37.776+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T21:19:37.791+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:18:22.168220+00:00 [queued]>
[2025-03-21T21:19:37.797+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:18:22.168220+00:00 [queued]>
[2025-03-21T21:19:37.797+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-21T21:19:37.815+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_cold_twitter_data> on 2025-03-21 16:18:22.168220+00:00
[2025-03-21T21:19:37.821+0500] {standard_task_runner.py:72} INFO - Started process 110875 to run task
[2025-03-21T21:19:37.824+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'coldpath_ingestion', 'ingest_cold_twitter_data', 'manual__2025-03-21T16:18:22.168220+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/coldpath.py', '--cfg-path', '/tmp/tmpii9kq6al']
[2025-03-21T21:19:37.825+0500] {standard_task_runner.py:105} INFO - Job 34: Subtask ingest_cold_twitter_data
[2025-03-21T21:19:37.863+0500] {task_command.py:467} INFO - Running <TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:18:22.168220+00:00 [running]> on host ubuntu
[2025-03-21T21:19:37.920+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='coldpath_ingestion' AIRFLOW_CTX_TASK_ID='ingest_cold_twitter_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T16:18:22.168220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T16:18:22.168220+00:00'
[2025-03-21T21:19:37.921+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T21:19:37.921+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T21:19:37.922+0500] {logging_mixin.py:190} INFO - Current task name:ingest_cold_twitter_data state:running start_date:2025-03-21 16:19:37.791334+00:00
[2025-03-21T21:19:37.922+0500] {logging_mixin.py:190} INFO - Dag name:coldpath_ingestion and current dag run status:running
[2025-03-21T21:19:37.922+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T21:24:56.002+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:24:56.003+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:01.074+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:01.076+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:06.137+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:06.139+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:11.188+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:11.188+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:16.251+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:16.252+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:21.317+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:21.319+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:26.381+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:26.381+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:31.450+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:31.451+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:36.518+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:36.519+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:41.586+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:41.588+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:46.644+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:46.644+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:51.712+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:51.713+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:25:56.752+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:25:56.753+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:01.824+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:01.826+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:06.853+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:06.854+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:11.919+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:11.921+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:16.982+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:16.983+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:22.049+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:22.050+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:27.106+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:27.107+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:32.161+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:32.162+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:37.230+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:37.231+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:42.291+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:42.292+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:47.363+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:47.364+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:52.424+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:52.424+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:26:57.476+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:26:57.476+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:02.543+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:02.544+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:07.567+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:07.567+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:12.628+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:12.629+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:17.697+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:17.698+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:22.768+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:22.769+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:27.791+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:27.791+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:32.822+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:32.822+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:37.881+0500] {local_task_job_runner.py:318} WARNING - Recorded pid 112528 does not match the current pid 110875
[2025-03-21T21:27:37.882+0500] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-03-21T21:27:40.878+0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T21:27:40.883+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T21:27:40.884+0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=coldpath_ingestion, task_id=ingest_cold_twitter_data, run_id=manual__2025-03-21T16:18:22.168220+00:00, execution_date=20250321T161822, start_date=20250321T162451, end_date=20250321T162740
[2025-03-21T21:27:40.907+0500] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-21T21:27:40.907+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-21T21:27:40.907+0500] {logging_mixin.py:190} INFO - Dag name:coldpath_ingestion queued_at:2025-03-21 16:18:22.182593+00:00
[2025-03-21T21:27:40.907+0500] {logging_mixin.py:190} INFO - Task hostname:ubuntu operator:PythonOperator
[2025-03-21T21:27:40.951+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T21:27:40.980+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T21:27:40.981+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
