[2025-03-21T21:32:45.763+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T21:32:45.777+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:31:22.588046+00:00 [queued]>
[2025-03-21T21:32:45.784+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:31:22.588046+00:00 [queued]>
[2025-03-21T21:32:45.784+0500] {taskinstance.py:2867} INFO - Starting attempt 2 of 1
[2025-03-21T21:32:45.801+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_cold_twitter_data> on 2025-03-21 16:31:22.588046+00:00
[2025-03-21T21:32:45.807+0500] {standard_task_runner.py:72} INFO - Started process 114496 to run task
[2025-03-21T21:32:45.811+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'coldpath_ingestion', 'ingest_cold_twitter_data', 'manual__2025-03-21T16:31:22.588046+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/coldpath.py', '--cfg-path', '/tmp/tmp1si_j1w2']
[2025-03-21T21:32:45.812+0500] {standard_task_runner.py:105} INFO - Job 35: Subtask ingest_cold_twitter_data
[2025-03-21T21:32:45.852+0500] {task_command.py:467} INFO - Running <TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:31:22.588046+00:00 [running]> on host ubuntu
[2025-03-21T21:32:45.906+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='coldpath_ingestion' AIRFLOW_CTX_TASK_ID='ingest_cold_twitter_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T16:31:22.588046+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T16:31:22.588046+00:00'
[2025-03-21T21:32:45.907+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T21:32:45.908+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T21:32:45.908+0500] {logging_mixin.py:190} INFO - Current task name:ingest_cold_twitter_data state:running start_date:2025-03-21 16:32:45.777980+00:00
[2025-03-21T21:32:45.908+0500] {logging_mixin.py:190} INFO - Dag name:coldpath_ingestion and current dag run status:running
[2025-03-21T21:32:45.908+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T21:42:30.987+0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-03-21T21:42:30.988+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-21T21:42:31.003+0500] {process_utils.py:132} INFO - Sending 15 to group 114496. PIDs of all processes in the group: [114506, 114496]
[2025-03-21T21:42:31.003+0500] {process_utils.py:87} INFO - Sending the signal 15 to group 114496
[2025-03-21T21:42:31.004+0500] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-21T21:42:31.007+0500] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/tashi/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/coldpath.py", line 15, in run_coldpath_script
    subprocess.run(["python3", script_name], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-21T21:42:31.011+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=114506, status='terminated', started='21:32:45') (114506) terminated with exit code None
[2025-03-21T21:42:31.029+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T21:42:31.038+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=114496, status='terminated', exitcode=0, started='21:32:45') (114496) terminated with exit code 0
