[2025-03-21T17:00:08.506+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:00:08.518+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_twitter.ingest_twitter scheduled__2025-03-21T11:00:00+00:00 [queued]>
[2025-03-21T17:00:08.524+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_twitter.ingest_twitter scheduled__2025-03-21T11:00:00+00:00 [queued]>
[2025-03-21T17:00:08.524+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-21T17:00:08.543+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_twitter> on 2025-03-21 11:00:00+00:00
[2025-03-21T17:00:08.550+0500] {standard_task_runner.py:72} INFO - Started process 37991 to run task
[2025-03-21T17:00:08.554+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_twitter', 'ingest_twitter', 'scheduled__2025-03-21T11:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/fetch_twitter.py', '--cfg-path', '/tmp/tmpk4rry_k7']
[2025-03-21T17:00:08.555+0500] {standard_task_runner.py:105} INFO - Job 11: Subtask ingest_twitter
[2025-03-21T17:00:08.604+0500] {task_command.py:467} INFO - Running <TaskInstance: fetch_twitter.ingest_twitter scheduled__2025-03-21T11:00:00+00:00 [running]> on host ubuntu
[2025-03-21T17:00:08.679+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_twitter' AIRFLOW_CTX_TASK_ID='ingest_twitter' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T11:00:00+00:00'
[2025-03-21T17:00:08.681+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T17:00:08.681+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T17:00:08.681+0500] {logging_mixin.py:190} INFO - Current task name:ingest_twitter state:running start_date:2025-03-21 12:00:08.518573+00:00
[2025-03-21T17:00:08.682+0500] {logging_mixin.py:190} INFO - Dag name:fetch_twitter and current dag run status:running
[2025-03-21T17:00:08.682+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:00:08.683+0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/fetch_twitter.py", line 10, in ingest_twitter_data
    auth = tweepy.OAuth1UserHandler(
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/auth.py", line 31, in __init__
    raise TypeError("Consumer key must be string or bytes, not "
TypeError: Consumer key must be string or bytes, not NoneType
[2025-03-21T17:00:08.688+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-21T17:00:08.688+0500] {logging_mixin.py:190} INFO - Task start:2025-03-21 12:00:08.518573+00:00 end:2025-03-21 12:00:08.687756+00:00 duration:0.169183
[2025-03-21T17:00:08.688+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ingest_twitter> dag:<DAG: fetch_twitter> dagrun:<DagRun fetch_twitter @ 2025-03-21 11:00:00+00:00: scheduled__2025-03-21T11:00:00+00:00, state:running, queued_at: 2025-03-21 12:00:02.064402+00:00. externally triggered: False>
[2025-03-21T17:00:08.688+0500] {logging_mixin.py:190} INFO - Failure caused by Consumer key must be string or bytes, not NoneType
[2025-03-21T17:00:08.689+0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fetch_twitter, task_id=ingest_twitter, run_id=scheduled__2025-03-21T11:00:00+00:00, execution_date=20250321T110000, start_date=20250321T120008, end_date=20250321T120008
[2025-03-21T17:00:08.710+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:00:08.711+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task ingest_twitter (Consumer key must be string or bytes, not NoneType; 37991)
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/fetch_twitter.py", line 10, in ingest_twitter_data
    auth = tweepy.OAuth1UserHandler(
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/auth.py", line 31, in __init__
    raise TypeError("Consumer key must be string or bytes, not "
TypeError: Consumer key must be string or bytes, not NoneType
[2025-03-21T17:00:08.726+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T17:00:08.738+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:00:08.738+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
